<div class="w-full flex justify-center px-4">
  <div class="w-full max-w-2xl space-y-6">
    {#if gClientInfo}
      <div class="rounded-lg border shadow-sm bg-white/70 backdrop-blur p-5 space-y-4">
        <header class="flex items-center justify-between">
          <h2 class="text-lg font-semibold">Google Photos OAuth Client</h2>
          {#if gClientInfo["is_activated"]}
            <span class="inline-flex items-center gap-1 rounded-full bg-emerald-100 text-emerald-700 px-3 py-1 text-xs font-medium border border-emerald-200">
              <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span> Active
            </span>
          {:else}
            <span class="inline-flex items-center gap-1 rounded-full bg-rose-100 text-rose-700 px-3 py-1 text-xs font-medium border border-rose-200">
              <span class="w-2 h-2 rounded-full bg-rose-500"></span> Inactive
            </span>
          {/if}
        </header>

        <div class="text-sm">
          <p class="font-mono break-all bg-gray-50 border rounded p-3 text-gray-700" aria-label="Client ID">
            {gClientInfo["client_id"]}
          </p>
        </div>

        {#if !gClientInfo["is_activated"]}
          <p class="text-xs text-gray-500">
            Your client is registered but not yet activated. Click Activate to start the OAuth flow.
          </p>
        {/if}
      </div>
    {:else}
      <div class="rounded-lg border shadow-sm bg-white/70 backdrop-blur overflow-hidden">
        <div class="p-5 space-y-4">
          <h2 class="text-lg font-semibold">Connect Google Photos</h2>
          <ul class="text-sm list-disc pl-5 space-y-1 text-gray-700">
            <li>Create an OAuth Client (Web application) in Google Cloud Console.</li>
            <li>Enable <b>Google Photos Library API</b>.</li>
            <li>Add redirect URI: <code class="bg-gray-100 px-1 py-0.5 rounded text-xs">http://localhost:5000/api/OAuthCallback</code></li>
            <li>Your data stays between you and Google.</li>
          </ul>

          <div class="mt-4">
            <label class="block text-xs font-medium mb-1 text-gray-600">Upload client_secret.json</label>
            <label class="group cursor-pointer w-full">
              <div class="flex flex-col items-center justify-center gap-2 rounded border-2 border-dashed p-6 bg-gradient-to-br from-blue-50 to-blue-100 hover:from-blue-100 hover:to-blue-200 transition">
                <span class="text-sm font-medium text-blue-700 group-hover:scale-105 transition">
                  {label}
                </span>
                <span class="text-[11px] text-blue-500">Only .json generated by Google Cloud Console</span>
              </div>
              <input
                id="file"
                type="file"
                class="hidden"
                accept=".json,application/json"
                on:change={handleClientUpload}
                aria-label="Upload Google OAuth client secret JSON"
              />
            </label>
          </div>
        </div>
      </div>
    {/if}

    {#if display_activation_button}
      <div class="flex justify-center">
        <button
          class="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 text-white font-medium px-5 py-2.5 rounded-md shadow-sm transition text-sm"
          on:click={activate}
        >
          Activate Google Photos
        </button>
      </div>
    {/if}
  </div>
</div>


<script lang="ts">
import { onMount } from "svelte";
  import { endpoints } from "./config";
  import { Layout } from "./components";


new Layout({
  title: "Google Photos - Hachi",
  currentPage: "/google-photos.html",
  showNavbar: true,
});


let gClientInfo = null;
let display_activation_button = false;
let label = "Upload Client secret json";

async function get_client_info(){
    const response = await fetch(endpoints.BASE_URL + "/api/gClientInfo");
    const data = await response.json();
    if (data['client_id_available']){
        gClientInfo = data;
        display_activation_button = !gClientInfo["is_activated"];
    }
}

onMount(()=>{
    get_client_info();
});

async function pollActivationStatus(){
    const response = await fetch(endpoints.BASE_URL + "/api/statusGAuthFlow");
    const data = await response.json();
    let isFinished = data["finished"];
    if (isFinished) {
        setTimeout(pollActivationStatus, 2000);
    } else {
        display_activation_button = false;
         alert("Account Activation: " + data["status"].toString());
         get_client_info();
    }
}

async function activate(event) {
    event.target.disabled = true;
    event.target.innerText = "activation in progress...";

    const response = await fetch(endpoints.BASE_URL + "/api/beginGAuthFlow");
    if (!response.ok) {
        alert("Some error occurred while starting authorization flow!");
        event.target.disabled = false;
        event.target.innerText = "Activate Google Photos";
    } else {
        setTimeout(pollActivationStatus, 1000);
    }
}

  function handleClientUpload(event) {
    let expected_redirect = "http://localhost:5000/api/OAuthCallback";
    label = "upload in progress..";
    event.preventDefault();
    console.log(event.target);
    event.target.disabled = true;

    var reader = new FileReader();
    reader.onload = function () {
      var client_data = JSON.parse(reader.result);
      let temp_keys = Object.keys(client_data);

      // client side checking for valid credentials..
      let is_web_app = temp_keys.includes("web");
      let redirect_uri_valid = false;

      if (is_web_app) {
        if (Object.keys(client_data["web"]).includes("redirect_uris")) {
          redirect_uri_valid =
            client_data["web"]["redirect_uris"].includes(expected_redirect);
        }
      }

      if (is_web_app === true && redirect_uri_valid == true) {
        let temp_data = new FormData();
        temp_data.append("client_data", reader.result);

        fetch(endpoints.BASE_URL + "/api/uploadClientData", {
          method: "POST",
          body: temp_data,
        }).then((response) => {
          if (response.ok == false) {
            alert("Some error occured !!");
          } else {
            label = "Upload Client secret json";
            get_client_info();
            event.target.disabled = false;
            display_activation_button = true;
          }
        });
      } else {
        alert(
          "Must be a webapp and redirect_uris must contain: " +
            expected_redirect
        );
        return;
      }
    };
    reader.readAsText(event.target.files[0]);
  }

</script>
